### ISSUE TITLE
importing foreign Java modules

### ISSUE THREAD

**Issue by Mrodent** [rzabini/gradle-jython#10]
I'm having a few more difficulties actually getting the thing to work ... for example, following a TDD methodology the first thing I want to do is write a failing test.  So I tweaked the Jython file sayHello.py so that its first two lines are
import java.lang
import org.junit

but then running the "jythonTask" then fails with "ImportError: No module named junit"

I then went back to gradle.build and in the dependencies block I added 
implementation 'junit:junit:4.12'  (this is already there as "testImplementation", of course)
and then
compile 'junit:junit:4.12'
... then I tried adding these lines to the testJython task itself.

I also tried manually including the junit .jar file (from the GRADLE_HOME area) in the PYTHON_PATH (external .jar) for the project (although this would kind of defeat the object of having a build tool and may be totally ignored by Gradle for all I know).  It still said "No module named junit".

Any idea what the solution is?

**Comment by rzabini** [comment]
I guess that when you use "import" in a Python file, it is expected to import a Python package, not a Java one. If you want to unit test a Python source, probably is better to go with the Python package unittest, as suggested here: https://stackoverflow.com/questions/4583429/writing-junit-tests-in-jython

**Comment by rzabini** [comment]
To include a java package in the classpath used at runtime by a JythonTask, you need to add the dependency to the `jython` configuration. Put this in your `build.gradle`:
```
dependencies { 
  jython 'junit:junit:4.12'
}
```
Then you can use classes in this jar, but, as far as I know, you need to import them with their full name. So in your `sayHello.py` you can write, for instance:
```
import org.junit.Assert as Assert

Assert.assertTrue(1==1)
```
HTH

**Comment by Mrodent** [comment]
Thanks again.

Still having problems.

My file sayHello.py and build.gradle are as simple as possible:
plugins {
	id 'java-library'
	id 'eclipse'
	id "com.github.rzabini.gradle-jython" version "1.0.6"
}
repositories {
    jcenter()
}
dependencies {
    api 'org.apache.commons:commons-math3:3.6.1'
    implementation 'com.google.guava:guava:23.0'
	testImplementation 'junit:junit:4.12'
	jython 'junit:junit:4.12'
}
task testJython(type:jython.JythonTask ) {
	script file('scripts/sayHello.py')
}


Fails like so:
Working Directory: D:\My Documents\software projects\EclipseWorkspace\GradleJythonTest
Gradle User Home: D:\apps\Mike.gradle
Gradle Distribution: Specific Gradle version 4.4.1
Gradle Version: 4.4.1
Java Home: D:\apps\Java\jdk1.8.0_121
JVM Arguments: None
Program Arguments: --scan
Build Scans Enabled: false
Offline Mode Enabled: false
Gradle Tasks: testJython

:jythonClasses
:testJython FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':testJython'.
> Could not normalize path for file 'D:\apps\Mike.gradle\caches\modules-2\files-2.1\org.python\jython-standalone\2.7.0\cdfb38bc6f8343bcf1d6accc2e1147e8e7b63b75\jython-standalone-2.7.0.jar;D:\apps\Mike.gradle\caches\modules-2\files-2.1\junit\junit\4.12\2973d150c0dc1fefe998f834810d68f278ea58ec\junit-4.12.jar;D:\apps\Mike.gradle\caches\modules-2\files-2.1\org.hamcrest\hamcrest-core\1.3\42a25dc3219429f0e5d060061f71acb49bf010a0\hamcrest-core-1.3.jar'.

... NB I'm on a Windows machine... but I can't see anything illegal about the path names.
NB2 I deleted and regenerated my entire GRADLE_HOME (D:\apps\Mike.gradle\): still the same problem...

**Comment by rzabini** [comment]
I made a new version which should probably fix the problem on Windows. Would you please try it?

**Comment by Mrodent** [comment]
Hi, 

Thanks for you continued help with this.  1.0.8 failed with this: 

"1.0.8: ImportError: No module named junit"

NB I have also (today) just set up a Linux (Mint Cinnamon 18.3) OS on my machine, to see whether I could indeed get it working in *nix ... and then I installed Eclipse and made a Gradle project... currently the testJython task is not yet showing up there: this may be because I haven't installed Jython properly there on the system: using apt-get installed a really old version (2.5) so I uninstalled that.

(NB I'm a bit of a beginner with Linux so I don't actually know how I go about installing Jython 2.7.2 as here https://github.com/jythontools/jython/releases after I've downloaded those files: could you possibly explain???)  ... also does your plugin need to find the command "jython" on the system PATH... or maybe it needs to find some environment variables???

**Comment by rzabini** [comment]
Are you importing a package (eg. org.junit) or a class?
From my undestanding of Jython, a "module" is a Java class, not a Java package; from your output it seems you tried to import a package, am I wrong?

There is no need to install Jython: it should be downloaded by Gradle and stored in its cache.

**Comment by Mrodent** [comment]
You're right... my mistake.  I just managed to get it to run (on my Windows system)  with version 1.0.8 - "from org.junit import Assert" worked OK.  So am closing this issue.  Thanks again.
