### ISSUE TITLE
Update gradle-jython version in README.md

### ISSUE THREAD

**Issue by alexanderkoller** [rzabini/gradle-jython#14]
Hi,

thanks for developing the gradle-jython plugin; it really helps with my work.

I recently added Python dependencies to a project that I had started based on the example build.gradle snippets in the [README.md](https://github.com/rzabini/gradle-jython#gradle--21), and ran into issue #3 . It is easy to fix this problem by replacing version "1.0.0" in the gradle-jython dependency with "1.0.9", but it took some digging to figure this out.

Could I ask you to change the version to 1.0.9 in the README.md and keep it updated to whatever the current version is? That would make the life of other users easier.

Best,
Alexander.

**Comment by rzabini** [comment]
Update README to reflect current version.
