### ISSUE TITLE
Jython plugin failing suddenly in gradle

### ISSUE THREAD

**Issue by sabdalla80** [rzabini/gradle-jython#17]
Hi,

Our gradle build has started failing last few days suddenly with the following error:

`00:32:46  Downloading troposphere, version 2.6.3 `
`00:32:46  inferred path is: https://pypi.python.org/simple/troposphere`
`Caused by: org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 5; The element type "meta" must be terminated by the matching end-tag "</meta>".`

I believe the error is in the `static URL findPackageArchive(name, version)` function in PackageFinder.groovy.
And more specifically on the XmlSlurper line #49 located here:
 https://github.com/rzabini/gradle-jython/blob/master/src/main/groovy/jython/util/PackageFinder.groovy#L49
 
 Our testing revealed that the Parser at line #49 seems to error out when it meets an non-terminated open html tag such as:
 `<meta name="pypi:repository-version" content="1.0">`
 

A sample `build.gradle` to reproduce.

` buildscript() {
        ...
  	dependencies {
        classpath "gradle.plugin.com.github.rzabini:gradle-jython:1.0.10"
      }
  }`
 ` apply plugin: "com.github.rzabini.gradle-jython"`
 ` jython {
	pypackage 'troposphere:2.6.3'
  }`

I appreciate any help in resolving this issue.

**Comment by rzabini** [comment]
Yes, you are right.
It seems that the meta tag has been added to the html page which lists all package versions in the Pypi site (e.g. https://pypi.org/simple/troposphere/).
The meta tag is not properly terminated by means of `/>` or `</meta>`, hence the XML parser fails.
Probably the quickest solution is to remove the meta tag just before parsing the html page text, I will look into it.

**Comment by sabdalla80** [comment]
Thanks for taking a look. I appreciate the help. I took a quick look yesterday and write some code, while it may not be perfect and doesn't cover all meta tag scenarios, I thought I'd share as it can be a starter.
`static String fixMalformedMetaTags(html) {

      List badLines  = new ArrayList<String>()
        def lines = html.split( '\n' )
        if(lines.size() > 0){
          for(String l: lines){
            if(l.contains("<meta") and !l.endsWith("/>"))
                badLines.add(l)  
          }
        }

        String fixedHtml
        for (String badLine : badLines) {
            String fixedLine = badLine.replace('>','/>')
            fixedHtml = html.replace(badLine,fixedLine)
        }

        return fixedHtml
     }`

**Comment by cdancy** [comment]
@rzabini can we have a new point release with this fix?

**Comment by rzabini** [comment]
Published v1.0.11. 
Thanks to @sabdalla80 for catching the issue.
