### ISSUE TITLE
Passing parameter arguments

### ISSUE THREAD

**Issue by simonharrer** [rzabini/gradle-jython#2]
Please add the ability to pass in arguments to the executed script. I want to call a script that is normally working on the command line and needs some parameters in the form `-c`.

**Comment by rzabini** [comment]
Although it is not explicitly mentioned in the README, JythonTask is a subclass of [JavaExec] (https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html) task from Gradle.
This means that you should be able to use the `args` property to add arguments to the command line, something like:

```gradle
task testJython (type:jython.JythonTask) {
    args 'scripts/test.py', 'foo', 'bar'
}
```
Does it work for you?

**Comment by simonharrer** [comment]
This would work perfectly. Thank you.
