### ISSUE TITLE
pypackage name must match case?

### ISSUE THREAD

**Issue by choyrim** [rzabini/gradle-jython#4]
it looks like the python dependency name must match the file names in pypi. when i try to specify sqlalchemy in lowercase, the build fails.
```
jython {
    pypackage 'sqlalchemy:0.8.5'
}
```

gradle logging shows that it seems to be having trouble finding the URL
```
Downloading sqlalchemy, version 0.8.5
inferred path is: https://pypi.python.org/simple/sqlalchemy
downloading https://pypi.python.org/simple/sqlalchemy/null

FAILURE: Build failed with an exception.
. . .
Caused by: java.lang.IllegalStateException: Could not download file
        at de.undercouch.gradle.tasks.download.DownloadExtension.configure(DownloadExtension.java:46)
. . .
```

If I go to the URL listing at https://pypi.python.org/simple/sqlalchemy , I see that the tar files are mixed case
```
Links for sqlalchemy

SQLAlchemy-1.1.9.tar.gz
SQLAlchemy-1.0.0b1.tar.gz
SQLAlchemy-0.3.11.tar.gz
SQLAlchemy-0.8.0.tar.gz
SQLAlchemy-0.6beta1.tar.gz
. . .
```

When I change it to match the case of the file at pypi, it works.
```
jython {
    pypackage 'SQLAlchemy:0.8.5'
}
```

using Gradle 3.2.1 and de.undercouch.download 3.2.0

**Comment by rzabini** [comment]
Yes, you are right. I think it may be due to the use of _equals_ instead of _equalsIgnoreCase_ while searching in the page text. I'll look into it.
