### ISSUE TITLE
left shift usage

### ISSUE THREAD

**Issue by choyrim** [rzabini/gradle-jython#5]
when using the plugin with Gradle 3.2.1, I get warnings about `<<` usage.
```
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
```

**Comment by rzabini** [comment]
Actually the source code of the plugin does not use the leftShift operator.
It may be due to another plugin, as I found here: https://github.com/gradle/gradle/issues/899.
Can you please run the build with _gradle --stacktrace_ and post the stack trace?
