### ISSUE TITLE
Python modules with "-" in indentifier can't be imported

### ISSUE THREAD

**Issue by hasenbanck** [rzabini/gradle-jython#6]
It seems that modules with a "-" in the identifier can't be imported with your plugin. It finds and download the module, but it won't copy the module content folder, since the folder name has the "-" replaced with a "_".

Example:
`
jython {
    pypackage 'requests-mock:1.3.0'
}
`

`
ImportError: No module named requests_mock
`

The import path in python is "requests_mock" (also the folder name). So the plugin needs to convert "-" into "_" in the identifier, or we need a way to define the real identifier of a dependency in such a case.

**Comment by rzabini** [comment]
Thank you for reporting the bug, I added a failing test case that shows the problem.
I am trying to figure out a solution: just converting the "-" into "_" passes the new test, but fails a previous one, in which the module "python-dateutil" is imported.
So I am thinking about adding the real identifier, as you suggested. Any suggestion?

**Comment by hasenbanck** [comment]
Why not sync the behavior with the other gradle jython module by [(hierynomus)](https://github.com/hierynomus/jython-gradle-plugin)?

So either the old style:

>dependencies {
>  jython ":python-dateutil:2.4.2:dateutil"
>}

Or the new style, which is more flexible:

>dependencies {
>  jython python("jmespath:jmespath.py:0.7.1") {
>    moduleName = "jmespath"
>  }
>  jython python(":python-dateutil:2.4.2") {
>    moduleName = "dateutil"
>  }
>}

>dependencies {
>  jython python(":six:1.9.0") {
>    useModuleName = false // Copy not to moduleName 'six', but rather to the root
>    copy {
>      from "six.py" // Will only copy six.py
>    }
>  }
>  jython python(":isodate:0.5.4") {
>    copy {
>      from "src/isodate" // Will copy the contents of the directory into the module directory
>    }
>  }
>}
